### ISSUE TITLE
[Bug]: Can't navigate to 'For You' from 'Interests' after selecting 'News' topic tag

### ISSUE THREAD

**Issue by marzaise** [android/nowinandroid#1614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!
**Steps to reproduce:**

- After launching the app, click on any topic tag from a news item (e.g., Headlines or Wear OS).
- Once you've navigated to this interest item, try clicking on the first tab of the Navigation Bar (For You).

**Current behavior**
Clicking on the first tab of the Navigation Bar (For You) does nothing.

**Expected behavior**
Clicking on the first tab of the Navigation Bar (For You) should navigate to 'For You' (or perhaps perform a back action in this case).

**Video**
[foryou_bug_nia.webm](https://github.com/user-attachments/assets/3b3e2284-3753-468a-8987-bb932229886d)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by padrecedano** [comment]
Hi. Show your `NiaNavHost` and `TopLevelDestination` content.

**Comment by sindrenm** [comment]
FWIW, I think this is slightly related to https://issuetracker.google.com/issues/308334893, where I have reported the same thing (see [#comment8](https://issuetracker.google.com/issues/308334893#comment8)).

**Comment by sindrenm** [comment]
A related issue here is that the app switches the active navigation bar tab from For You to Interests when you tap a topic from inside of the For You tab. This, IMO, should never happen. The app should instead remain on the same For You tab, but with the interest content that the user requested to see.

The problem then lies in the way the app checks if a route exists in the hierarchy. Since the `TopicScreen`'s destination only exists in a graph in `InterestsListDetailScreen`, the hierarchy check will return `true` only for the Interests top level route:

```kotlin
private fun NavDestination?.isRouteInHierarchy(route: KClass<*>) =
    this?.hierarchy?.any {
        it.hasRoute(route)
    } ?: false
```
