### ISSUE TITLE
[Bug]: Excessive underscores in test function names

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

For example, in https://github.com/android/nowinandroid/blob/607c24e7f7399942e278af663ea4ad350e5bbc3a/core/data/src/test/java/com/google/samples/apps/nowinandroid/core/data/repository/OfflineFirstUserDataRepositoryTest.kt

Check all codebase and use maximum of 2 underscores per test in the format: `given_when_then`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kenny50** [comment]
I can take this

**Comment by Kenny50** [comment]
@dturner  I am struggle with some decision

1. ForYouViewModel
Original test naming is expect_condition, like `stateIsLoadingWhenFollowedTopicsAreLoading`, I don't understand the reason, but I prefer using direct statement like `whenFollowedTopicsAreLoading_thenStateIsLoading`
2. ListToMapMigration, IntToStringMigration
I never heard naming convention in test start with capitalize, I would like to change `ListToMapMigration_should_migrate_bookmarks` into `listToMapMigration_shouldMigrateBookmarks`
3. given_then format
I am not sure which one for given_then format is better, `offlineFirstAuthorsRepositoryAuthorsStream_isBackedByAuthorsDao` or `offlineFirstAuthorsRepository_authorsStream_isBackedByAuthorsDao`, since in other case I will choose `offlineFirstAuthorsRepository_syncDeletesItems_markedDeletedOnNetwork` and `offlineFirstAuthorsRepository_syncPullsFromNetwork`, it would be more consistency with second one, but meanwhile it break the given_when_then format
4. NewsResourceDaoTest
`newsResourceDao_filters_items_by_topic_ids_or_author_ids_by_descending_publish_date` test with long condition expression would looks like `newsResourceDao_filtersItemsByTopicIdsOrAuthorIdsByDescendingPublishDate` , but this change doesn't make the name more readable, any advice?

**Comment by chanjungkim** [comment]
I think that looks fine @Kenny50

**Comment by SimonMarquis** [comment]
This could be a lint 🤓 and pretty easy to write too.
But I'm not sure if this would fit in such a "app architecture showcase" repository.
An other simpler solution is to simply use Kotlin's backticks for method names and use spaces.

```kotlin
@Test
fun `given X when Y then Y`()
```

@dturner let us know what's the best approach here.

**Comment by SimonMarquis** [comment]
Although, there already is a `DesignSystemDetector` custom lint, so, this might not be a bad idea to add one for test method conventions after all?

**Comment by SimonMarquis** [comment]
Backticks will not work on Android instrumented tests, bit they work fine on regular unit tests.
