### ISSUE TITLE
[Documentation]: Why is NiaAppState uses @composable get function instead of global instance of derivedStateOf ?

### ISSUE THREAD

**Issue by thegarlynch** [android/nowinandroid#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Page URL (type "NEW" for a new page suggestion)

NEW

### What's the documentation problem or suggestion?

Why is NiaAppState uses @Composable get function instead of global instance of derivedStateOf ? 

(https://github.com/android/nowinandroid/blob/main/app/src/main/java/com/google/samples/apps/nowinandroid/ui/NiaAppState.kt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Is the question for why we have a `rememberNiaAppState` method, as opposed to a global singleton?

`NiaAppState` has to live within a Composable scope, since it has access to a `NavHostController`. Having an isolated entry-point to create one also makes it a lot easier to test `NiaAppState` in isolation in a test, even if there will only be one ever created in the production application.

**Comment by thegarlynch** [comment]
`@Composable get` ? 
how is this different than using `derivedStateOf` directly.
