### ISSUE TITLE
[Bug]: The screen goes up after bookmarking an item

### ISSUE THREAD

**Issue by SaeedNoshadi89** [android/nowinandroid#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When I bookmark an article on the home page, the page scrolls up and returns to the default position.

https://user-images.githubusercontent.com/50018300/201514331-e2aa7885-855b-440b-8367-0395fbc8b5de.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shapcode** [comment]
This appears to be due to ForYouViewModel emitting a `NewsFeedUiState.Loading` each time a new userData is received (the effect of changing the saved state of an item), which is handled in NewsFeed by not calling `items()` (so all items are removed, then added again when NewsFeedUiState.Success arrives).

Removing the `onStart` from `mapToFeedState` avoids the flicker and scroll position reset, but might introduce some other undesired effects.
