### ISSUE TITLE
New developer trying my hand at this 

### ISSUE THREAD

**Issue by Mcgirty** [android/nowinandroid#539]
https://developer.android.com/studio/run/emulator-acceleration#vm-mac

**Comment by dturner** [comment]
Since you're a new developer you probably didn't realise but you've filed an issue on the Now in Android app project. Issues are for letting the project team (and everyone else) that there's a bug in the project, or that you have a feature request. This doesn't seem to be either of those. Please open a new issue if there's something specific you'd like to report.
