### ISSUE TITLE
[FR]: Support of foldable devices, devices with split-screen mode and picture-in-picture usage

### ISSUE THREAD

**Issue by Gelassen** [android/nowinandroid#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

I don't have much exposure to foldable device, devices with split-screen mode or picture-in-picture usage. By reading this [introduction](https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes#window_size_classes) of new different screen dimensions support, **it would be good also to see the best practices of the app architecture with its support**. 

One extra point. The ```ConstraintLayout``` with its GUI-powered development is promoted as a core solution to mitigate diversity of screens dimensions, but on another hand the ```Compose``` is actively promoted to replace the existing paradigm in android native development and you still have to manually verify all UI blocks relationships which from my perspective even more difficult compare with tradition ways.      

### Describe the solution

Please add support of foldable devices, devices with split-screen mode or picture-in-picture usage to this demo app. 

### Additional context

Please note, even 8 years ago the cost of mobile app development on 50% was built based on UI development. Nowadays you even increase UI complexity which increase the cost of UI development even more rather than 50% of the app budget. UI is important, but it is useless without business logic. I believe if you continue work on making android UI even more diverse and complex, you will rise the entry level on this app market and reduce amount of entrepreneurs with fresh ideas.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexvanyo** [comment]
Thank you for the feedback!

Currently, this project already works quite well across different screen sizes, free-form window and multi-window mode: handling different orientations and configuration changes, and adjusting UI depending on the screen size. For example, switching between a navigation rail and navigation bar based on the window size class for better ergonomics, and the main feed uses a `LazyVerticalGrid` to show multiple columns when space allows. We also have previews set-up to verify UI across different sizes, as well as tests for different sizes as well.

For foldable devices specifically, folding and unfolding should maintain state and the UI should adjust appropriately just like multi-window mode, but we don't have any table-top or other posture support at the moment. For most use cases, the inner screen of a dual-screen foldable device should function just like a small-ish tablet screen.

For picture-in-picture, since we don't play any media in-app, entering that mode doesn't make a lot of sense.

We are continuing to make the project work even better across different screens (both for the user and for development), so stay tuned for additional improvements!
