### ISSUE TITLE
[Bug]: shouldShowSettingsDialog is not persisted through activity recreation

### ISSUE THREAD

**Issue by alexvanyo** [android/nowinandroid#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

When the settings dialog is open, causing activity recreation through resizing or rotating the app causes the settings dialog to close.

We should likely keep this state saved via saved instance state so that the settings dialog remains open.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KwakEuiJin** [comment]
@alexvanyo  I want to resolve to this issue. can I work on this?

**Comment by KwakEuiJin** [comment]
> @alexvanyo I want to resolve to this issue. can I work on this?

@alexvanyo I already pushed the modified logic to my personal repository. Can I request for Pull request? 😁

**Comment by bubenheimer** [comment]
You guys may want to keep a screen recording of the old behavior for documentation purposes, demonstrating the importance of correctly handling screen rotation. On the start screen the "broken" behavior is super confusing to a new user, because the dialog disappears and the start screen reappears with a completely different layout, meaning I had no idea where I was.
