### ISSUE TITLE
Many errors in project structure

### ISSUE THREAD

**Issue by mobilekosmos** [android/nowinandroid#617]
No build type in module xy matches build type "benchmark"

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1061543/222617047-d4eb9dcc-5121-4c2f-ac25-f23e1dc2f970.png">

Android Studio Electric Eel | 2022.1.1 Patch 2

**Comment by priyanshnama** [comment]
please assign this to me

**Comment by SimonMarquis** [comment]
This is unfortunately the expected behavior here.
The `app` module is setup to fallback to the `release` build type.
Adding default `benchmark` build types on other modules will introduce unexpected behaviors, as we really want to test the `release` code during benchmarks.

https://github.com/android/nowinandroid/blob/0c8457099d13ebbfed75d4db59cfe43d3d527b8c/app/build.gradle.kts#L59

**Comment by SimonMarquis** [comment]
I think we can close this as "unfixable", wdyt @dturner?
