### ISSUE TITLE
[Bug]: AndroidCIwithGMD is extremely flaky.

### ISSUE THREAD

**Issue by dturner** [android/nowinandroid#787]
The [GMD CI workflow](https://github.com/android/nowinandroid/actions/workflows/AndroidCIWithGmd.yaml) is extremely flaky and fails ~50% of the time. This stops us confidently knowing at-a-glance whether a PR has broken anything. 

The failure seems to be: 

```
* What went wrong:
See the complete report at file:///Users/runner/work/nowinandroid/nowinandroid/build/reports/configuration-cache/5ry13d5z8qfsx1fxfjjv5vdgg/a6knu9g6nk63az4cyh3cpu197/configuration-cache-report.html
Execution failed for task ':app:pixelcapi30aospatdSetup'.
478 actionable tasks: 4 executed, 474 up-to-date
> A failure occurred while executing com.android.build.gradle.internal.tasks.ManagedDeviceSetupTask$ManagedDeviceSetupRunnable
   > java.lang.IllegalStateException: Snapshot setup ran successfully, but the snapshot failed to be created. This is
     likely to a lack of disk space for the snapshot. Try the cleanManagedDevices
     task with the --unused-only flag to remove any unused devices for this project.
```

For now, I have manually disabled this workflow but it'd be good to get to the bottom of why this is so flaky.

**Comment by SimonMarquis** [comment]
I don't think this is actually related to disk space as Github Action already provides enough of it (though we might add a log to detect the remaining disk space in the workflow).
Also the logs already tell us there are no devices to delete for every module:

```
Successfully deleted 0 managed devices.
```

There might be some log file we can extract when this error occurs.

**Comment by SimonMarquis** [comment]
Testing `gradlew ciDemoDebugAndroidTest` locally on macos also triggers the same errors from time to time.
There are no logs in `~/.android/avd/gradle-managed/*` that could help troubleshoot.
I was not able to reproduce the issue locally with `--no-parallel --max-workers=1`, I'll try multiple runs on GA.
- #792

**Comment by SimonMarquis** [comment]
FWIW, I've created a bug report on the Android issue tracker https://issuetracker.google.com/issues/287312019

**Comment by mrk-han** [comment]
**Runner**

I recommend swapping away from the macOS runner, it is a 3-core VM with very little memory. Is there any way we can get this project on Github's Larger runners? The linux runners with KVM have been a lot more stable in my benchmarks.

Since this project is open-source, we get free runners, but not larger runners. 

I believe Github is bringing KVM to the free 2-core runners, per my last conversations with their product owner when he reached out for feedback... but I'm not sure the timeline or if it will be feasible at all for GH to allow free-tier to access KVM. 

If we can get to the Larger Runners, the 4-Core Ubuntu runner is very affordable, and has 32gigs of memory.

I want to also say, if we can get Android emulators to run stably with GMD on the base macOS runner that GitHub offers, it would be a huge deal for every open-source Android project. I'd be happy to help contribute to the cause.

**Emulator Image**
My testing with the `aosp_atd` runner has been less than stellar in my benchmarks, but I was not using GMD. Is this occurring on other images or is it isolated to aosp_atd? Can we eliminate that variable?

**Comment by mrk-han** [comment]
If this is happening on Linux runners as well, especially with KVM enabled, then of course it'd definitely be worth addressing a core bug in the framework.

**Comment by JoseAlcerreca** [comment]
> I recommend swapping away from the macOS runner, it is a 3-core VM with very little memory.

Instrumentation tests are much more reliable than GMD at the moment, and they run on the same VM.

**Comment by SimonMarquis** [comment]
What do you mean by `Instrumentation tests`? 🤔

**Comment by JoseAlcerreca** [comment]
Sorry, I meant regular emulators handled by the reactivecircus action.
