### ISSUE TITLE
[Bug]: Wrong text color in dark mode

### ISSUE THREAD

**Issue by SimonMarquis** [android/nowinandroid#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

Also, I'm not sure about the correctness of the phrase `Try another search or explorer Interests to browse topics`

![image](https://github.com/android/nowinandroid/assets/1921278/16d2330e-30d8-41b3-b3a1-cc004f957073)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
It seems like `androidx.compose.foundation.text.ClickableText` doesn't respect `NiaTheme`'s  theme.

**Comment by si-huynh** [comment]
Digging deep into ClickableText, we can see that its default style is `TextStyle.default`, which is why it doesn't respect the current theme. On the other hand, the default style of Text is wrapped by `compositionLocalOf`, which allows it to get the current theme's text color.

I still haven't figured out why they must work like this.

**Comment by RivanParmar** [comment]
The phrase would be accurate, if the word were `explore` instead of `explorer`.

Also the phrase `Sorry, there is no content found for your search "aaa"` could be rephrased to something like `No matches found for "aaa"`? As the words don't fit in too well.

**Comment by SilviaGarciaBouza** [comment]
Could you take a look to this [PR](https://github.com/android/nowinandroid/pull/847) ? @SimonMarquis @si-huynh @RivanParmar
